datastore:
  image: mongo
  restart: always
  ports:
    - "27017:27017"
  environment:
    MONGO_INITDB_ROOT_USERNAME: mongo_user
    MONGO_INITDB_ROOT_PASSWORD: mongo_secret"
frontend:
  build: .
  command: python -u __init__.py
  ports: 
    - "5000:5000"
  volumes:
    - .:/todo
  links:
    - datastore